language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - osx
env:
  - RUST_BACKTRACE=1
before_script:
  - rustc --version
  - cargo --version
  - rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - cargo build --verbose
  - sh run_tests.sh
