name: test-rust-nightly

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-rust-stable:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: sh run_tests.sh
